### ISSUE TITLE
Upgrade to Tokio 0.2

### ISSUE THREAD

**Issue by mre** [mre/tokio-batch#11]
In https://github.com/mre/tokio-batch/pull/10 we try to move to Tokio 0.2.
Unfortunately, a lot has changed and the update requires some effort.

Mainly, the unit tests need fixing because `tokio::run` is no longer part of Tokio.
Instead, it's `tokio::test` now. See [here](https://github.com/tokio-rs/tokio/issues/1235) for more info.

If someone wants to take over, that would be a great opportunity to start with async Rust and Tokio.

**Comment by leshow** [comment]
I think I can take this one

**Comment by mre** [comment]
Done by @leshow in #12. Thanks a lot!
