### ISSUE TITLE
Rename project?

### ISSUE THREAD

**Issue by mre** [mre/tokio-batch#13]
The Rust async ecosystem is moving fast and this crate no longer depends on Tokio.
The only dependency we have is on `Stream` from the `futures` crate.
I was wondering if we should reflect that in the project name.

The two names that I favor at the moment are `futures-batch` and `async-batch` with a slight tendency towards `futures-batch`. I considered `stream-batch`, but it doesn't have the same ring to it.

Would be interested in getting your opinions @doyoubi, @leshow, @spebern, and @wngr.

**Comment by leshow** [comment]
I think this is a good idea. I like `futures-batch` also; I think it will be more discoverable than `async-batch`.

**Comment by doyoubi** [comment]
Yeah, I think `futures-batch` is easier to be found since it's relying on the `futures` ecosystem.

**Comment by spebern** [comment]
I also like `futures-batch`.
