### ISSUE TITLE
tokio-timer only supports low resolution timer

### ISSUE THREAD

**Issue by doyoubi** [mre/tokio-batch#4]
Hi,

Great lib for batching!!

Just a small problem.
The resolution of `tokio-timer` is too low. The smallest duration is 1 millisecond.
When batching syscall, we need to use a higher resolution timer.

`futures-timer` fits the needs but it requires changing the type of the Error returned.
Maybe you can consider moving from `tokio-timer` to `futures-timer`.

**Comment by mre** [comment]
Oh that's an interesting use-case for sure.
If there aren't any downsides, we could make the switch.
Since we are still in 0.x territory (non-stable) it's fine if we change the error type.

Would you mind creating a pull request for that if you find the time? 😊

**Comment by mre** [comment]
@yoshuawuyts fyi. Sounds like something that you might find interesting.

**Comment by doyoubi** [comment]
Sure! It's just a drop-in replacement.

I'm testing to see whether there are some other problems. I will write some feedback here.

**Comment by mre** [comment]
This feature has landed now thanks to @doyoubi. Hurray! 🎉 
I've cut a new release and updated the docs to reflect our support for high-resolution timers now.
